modLoader="javafml"

loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="MerlinKitsune, Nintyfive95"
logofile="icon.png"
description='''
A common library for the Astral Dice mod. It includes cross-platform implementations and supports functional integration with other mods.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
